# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  richssnackrack:
    build:
      context: "/Users/richardhaynes/Developer/Projects/C#/RichsSnackRack/RichsSnackRack"
      dockerfile: "RichsSnackRack/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/RichsSnackRack.dll"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/RichsSnackRack.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "richssnackrack:dev"
    ports: []
    volumes:
    - "/Users/richardhaynes/Developer/Projects/C#/RichsSnackRack/RichsSnackRack/RichsSnackRack:/app:rw"
    - "/Users/richardhaynes/Developer/Projects/C#/RichsSnackRack/RichsSnackRack:/src:rw"
    - "/Users/richardhaynes/.nuget/packages:/root/.nuget/packages"
    working_dir: "/app"
