version: '3.4'

services:
  richssnackrack:
    depends_on:
    - db
    image: ${DOCKER_REGISTRY-}richssnackrack
    build:
      context: .
      dockerfile: RichsSnackRack/Dockerfile
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'Snacks'
      MYSQL_ROOT_PASSWORD: 'Password1'
    volumes:
    - localdbdata:/var/lib/mysql
    restart: always
    ports:
    - '3306:3306'
volumes:
    localdbdata:
      driver: local
